### ISSUE TITLE
How to export

### ISSUE THREAD

**Issue by ghost** [speters/arduino-soundplay#1]
Hi  
id tryed BTcSE30BETA.
How can i export the sounds like you did ?

Thanks in advance.

**Comment by speters** [comment]
I used `xxd` (a standard program on the Unix/Linux console) to convert the binary _.btc_ files into a _.h_ C header file.
See the [Makefile](https://github.com/speters/arduino-soundplay/blob/master/Makefile) for a conversion example.

There are various other utilities which do the same (hexdump, bin2c, bin2h ...).

**Comment by ghost** [comment]
Ok i got it work.

Now id loaded and played my own .h files.
But they repeat 3 times everytime.
Can i do it so, that the sound play only once ?

My play code should run once in setup loop.

```
void setup()
{
#ifdef DEBUG
    Serial.begin(115200);
#endif
    pinMode(A1, INPUT);

    soundplayer_setup();


    //delay(3000);
    soundplayer_play_ds((uint16_t) &mysound, mysound_len, SOUND_FORMAT_PCM,1);
    delay(1000);


}
```

Im sure id made sth. wrong.
Thanks in advance
(sorry for my english)
